version: 2.1
orbs:
  win: circleci/windows@2.2.0
  slack: circleci/slack@4.0
jobs:
  test:
    executor:
      name: win/default
      size: "medium"
    working_directory:  ~/amo-tests/

    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install --no-deps -r ./requirements.txt
      - run:
          name: Install geckodriver
          command: choco install selenium-gecko-driver
      - run:
          name: Install Firefox
          command: choco install firefox-nightly --pre
      - run:
          name: Run tests
          environment:
            MOZ_HEADLESS: 1
            PYTEST_ADDOPTS: -n 2
          command: pytest test_home.py::test_click_header_explore --driver Firefox --variables stage.json
          no_output_timeout: 30m
      - store_artifacts:
          path: ui-test-release.html
      - slack/notify:
          event: fail
          template: basic_fail_1
            # When there is a successful deployment, send a notification with a different template.
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
workflows:
  commit_workflow:
    jobs:
      - test
      - slack/on-hold:
          context:
            - slack-secrets
          requires:
            - test
      - pause_workflow:
          type: approval
          requires:
            - test
            - slack/on-hold
  scheduled_stage_release_run:
    triggers:
      - schedule:
          # the workflow runs each Wednesday at 05:00 UTC
          cron: "0 5 * * 3"
          filters:
            branches:
              only: master
    jobs:
      - test
