version: 2.1
orbs:
  win: circleci/windows@2.2.0
  slack: circleci/slack@4.3.3
jobs:
  test:
    executor:
      name: win/default
      shell: bash.exe
      size: "medium"
    working_directory:  ~/amo-tests/

    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install --no-deps -r ./requirements.txt
      - run:
          name: Install geckodriver
          command: choco install selenium-gecko-driver
      - run:
          name: Install Firefox
          command: choco install firefox-nightly --pre
      - run:
          name: Run tests
          environment:
            MOZ_HEADLESS: 1
            PYTEST_ADDOPTS: -n 2
          command: pytest test_home.py::test_click_header_explore --driver Firefox --variables stage.json
          no_output_timeout: 10m
      - store_artifacts:
          path: ui-test-release.html
      - slack/notify:
          channel: 'C01SUNKTM9V'
          custom: |
            {
            	"blocks": [
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": "Current Job: $CIRCLE_JOB"
            			}
            		},
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": ":white_check_mark: AMO Sanity run competed successfully"
            			},
            			"accessory": {
            				"type": "button",
            				"text": {
            					"type": "plain_text",
            					"text": "View",
            					"emoji": true
            				},
            				"value": "click-me",
            				"url": "https://app.circleci.com/pipelines/github/amot3st",
            				"action_id": "button-action"
            			}
            		}
            	]
            }
          event: pass
workflows:
  commit_workflow:
    jobs:
      - test:
          context: slack-secrets
