version: 2.1
orbs:
  win: circleci/windows@2.2.0
  slack: circleci/slack@4.0
jobs:
  test:
    executor:
      name: win/default
      size: "medium"
    working_directory:  ~/amo-tests/

    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install --no-deps -r ./requirements.txt
      - run:
          name: Install geckodriver
          command: choco install selenium-gecko-driver
      - run:
          name: Install Firefox
          command: choco install firefox-nightly --pre
      - run:
          name: Run tests
          environment:
            MOZ_HEADLESS: 1
            PYTEST_ADDOPTS: -n 2
          command: pytest test_home.py::test_click_header_explore --driver Firefox --variables stage.json
          no_output_timeout: 10m
      - store_artifacts:
          path: ui-test-release.html
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
workflows:
  commit_workflow:
    jobs:
      - test:
          context: slack-secrets
